import { createHash } from "node:crypto";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pluginDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(pluginDir, "..");
const pluginSrcDir = path.join(repoRoot, "plugin-src");
const pluginSourcePath = path.join(repoRoot, "plugin", "Plugin.luau");
const pluginOutputPath = path.join(repoRoot, "plugin", "Plugin.rbxm");
const pluginManifestPath = path.join(repoRoot, "plugin", "Plugin.build.json");
const pluginChildModules = [
  "Clipboard",
  "PathHelpers",
  "Photo",
  "Playscript",
  "Reflection",
  "RemoteCodec",
];

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: pluginSrcDir,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function gitText(args) {
  const result = spawnSync("git", args, {
    cwd: repoRoot,
    encoding: "utf8",
    shell: false,
  });
  if (result.status !== 0) return null;
  const value = String(result.stdout || "").trim();
  return value || null;
}

// The checked-in plugin artifact must be reproducible across commits, so local
// source builds use a stable label. Release jobs provide GITHUB_SHA, while
// ad-hoc packaging can opt into an exact revision with ROSYNC_BUILD_COMMIT.
const configuredCommit = process.env.ROSYNC_BUILD_COMMIT || process.env.GITHUB_SHA || "source";
const buildCommit = String(configuredCommit).slice(0, 12);
const configuredDirty = process.env.ROSYNC_BUILD_DIRTY;
const buildDirty =
  configuredDirty === "true" ||
  (configuredDirty !== "false" &&
    buildCommit !== "source" &&
    String(gitText(["status", "--porcelain", "--untracked-files=no"]) || "").length > 0);

await mkdir(path.join(pluginSrcDir, "src"), { recursive: true });
await Promise.all([
  copyFile(
    pluginSourcePath,
    path.join(pluginSrcDir, "src", "RoSync.server.luau"),
  ),
  ...pluginChildModules.map((moduleName) =>
    copyFile(
      path.join(repoRoot, "plugin", `${moduleName}.luau`),
      path.join(pluginSrcDir, "src", `${moduleName}.luau`),
    ),
  ),
]);
await writeFile(
  path.join(pluginSrcDir, "src", "BuildInfo.luau"),
  [
    "-- Generated by plugin/build-plugin.mjs. Do not edit.",
    "return {",
    `\tcommit = ${JSON.stringify(buildCommit)},`,
    `\tdirty = ${buildDirty ? "true" : "false"},`,
    "}",
    "",
  ].join("\n"),
  "utf8",
);

const rojoProject = JSON.parse(
  await readFile(path.join(pluginSrcDir, "plugin.project.json"), "utf8"),
);
for (const moduleName of pluginChildModules) {
  const expectedPath = `src/${moduleName}.luau`;
  const configuredPath = rojoProject?.tree?.RoSync?.[moduleName]?.$path;
  if (configuredPath !== expectedPath) {
    throw new Error(
      `plugin.project.json must package RoSync.${moduleName} from ${expectedPath}`,
    );
  }
}

if (process.env.ROSYNC_SKIP_WALLY !== "1") {
  run("wally", ["install"]);
}
run("rojo", ["build", "plugin.project.json", "--output", "../plugin/Plugin.rbxm"]);

const pluginSource = await readFile(pluginSourcePath, "utf8");
const pluginVersion = pluginSource.match(
  /local PLUGIN_VERSION_STRING = "([^"]+)"/,
)?.[1];
const protocolVersion = Number(
  pluginSource.match(/local PLUGIN_PROTOCOL_VERSION = (\d+)/)?.[1],
);
if (!pluginVersion || !Number.isSafeInteger(protocolVersion)) {
  throw new Error("Could not read plugin version/protocol constants from plugin/Plugin.luau");
}
const artifactBytes = await readFile(pluginOutputPath);
await writeFile(
  pluginManifestPath,
  `${JSON.stringify({
    schemaVersion: 1,
    artifact: "Plugin.rbxm",
    sha256: createHash("sha256").update(artifactBytes).digest("hex"),
    pluginVersion,
    protocolVersion,
    buildCommit,
    buildDirty,
  }, null, 2)}\n`,
  "utf8",
);
