//! Bounded, short-lived artifact uploads for daemon-local consumers.
//!
//! The store deliberately keeps upload bodies out of memory. A lease owns a
//! private staging file below the configured artifact directory; callers append
//! chunks at an exact offset and then atomically finalize the file. Lease tokens
//! are generated by the operating-system CSPRNG and only a SHA-256 digest of a
//! token is retained in memory.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fmt;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, MutexGuard};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const ID_RANDOM_BYTES: usize = 24;
const TOKEN_RANDOM_BYTES: usize = 32;
const RANDOM_COLLISION_RETRIES: usize = 16;
const MAX_SAFE_FILENAME_BYTES: usize = 120;
const MAX_MIME_BYTES: usize = 255;
const DEFAULT_FINALIZED_TTL: Duration = Duration::from_secs(15 * 60);
const DEFAULT_TOTAL_BYTES_MULTIPLIER: u64 = 4;
const DEFAULT_MAX_PENDING_LEASES: usize = 16;

/// A concurrency-safe store for bounded artifact uploads.
///
/// Clones share leases and finalized metadata. The supplied root is created and
/// canonicalized during construction, so every returned artifact path is
/// absolute and remains below that root.
#[derive(Clone)]
pub struct ArtifactStore {
    root: Arc<PathBuf>,
    max_bytes: u64,
    lease_ttl: Duration,
    finalized_ttl: Duration,
    max_total_bytes: u64,
    max_pending_leases: usize,
    max_pending_bytes: u64,
    inner: Arc<Mutex<StoreInner>>,
}

#[derive(Default)]
struct StoreInner {
    leases: HashMap<String, PendingArtifact>,
    artifacts: HashMap<String, FinalizedArtifact>,
    pending_bytes: u64,
    finalized_bytes: u64,
    next_access_sequence: u64,
}

struct FinalizedArtifact {
    metadata: ArtifactMetadata,
    expires_at: Instant,
    last_access_sequence: u64,
}

struct PendingArtifact {
    token_hash: [u8; 32],
    filename: String,
    mime: String,
    staging_path: PathBuf,
    final_path: PathBuf,
    expected_size: Option<u64>,
    reserved_bytes: u64,
    bytes_written: u64,
    hasher: Sha256,
    created_at_unix_ms: u64,
    expires_at: Instant,
}

/// Credentials and constraints returned when an upload lease is created.
///
/// The token authorizes appends, finalization, and cancellation for this lease
/// only. It becomes unusable as soon as the lease is finalized, aborted, or
/// expires.
#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactLease {
    pub id: String,
    pub token: String,
    pub filename: String,
    pub mime: String,
    pub max_bytes: u64,
    pub expected_size: Option<u64>,
    pub expires_at_unix_ms: u64,
}

impl fmt::Debug for ArtifactLease {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ArtifactLease")
            .field("id", &self.id)
            .field("token", &"[REDACTED]")
            .field("filename", &self.filename)
            .field("mime", &self.mime)
            .field("max_bytes", &self.max_bytes)
            .field("expected_size", &self.expected_size)
            .field("expires_at_unix_ms", &self.expires_at_unix_ms)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppendReceipt {
    pub id: String,
    pub offset: u64,
    pub bytes_appended: u64,
    pub total_bytes: u64,
}

/// Metadata for a successfully finalized artifact.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactMetadata {
    pub id: String,
    pub filename: String,
    pub mime: String,
    pub path: PathBuf,
    pub size: u64,
    pub sha256: String,
    pub created_at_unix_ms: u64,
    pub finalized_at_unix_ms: u64,
}

#[derive(Debug)]
pub enum ArtifactError {
    Io(io::Error),
    InvalidConfig(&'static str),
    InvalidFilename(String),
    InvalidMime,
    InvalidChecksum,
    LeaseNotFound,
    InvalidToken,
    LeaseExpired,
    OffsetMismatch { expected: u64, actual: u64 },
    ByteLimitExceeded { limit: u64, attempted: u64 },
    ExpectedSizeExceeded { expected: u64, attempted: u64 },
    PendingLeaseLimitExceeded { limit: usize },
    PendingByteLimitExceeded { limit: u64, attempted: u64 },
    SizeMismatch { expected: u64, actual: u64 },
    ChecksumMismatch { expected: String, actual: String },
    StagingSizeMismatch { expected: u64, actual: u64 },
    RandomIdCollision,
    LockPoisoned,
}

impl fmt::Display for ArtifactError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "artifact I/O error: {error}"),
            Self::InvalidConfig(message) => {
                write!(formatter, "invalid artifact configuration: {message}")
            }
            Self::InvalidFilename(name) => write!(formatter, "unsafe artifact filename: {name:?}"),
            Self::InvalidMime => write!(formatter, "invalid artifact MIME type"),
            Self::InvalidChecksum => write!(
                formatter,
                "expected SHA-256 must be 64 hexadecimal characters"
            ),
            Self::LeaseNotFound => write!(formatter, "artifact lease was not found"),
            Self::InvalidToken => write!(formatter, "artifact lease token is invalid"),
            Self::LeaseExpired => write!(formatter, "artifact lease has expired"),
            Self::OffsetMismatch { expected, actual } => {
                write!(
                    formatter,
                    "artifact chunk offset {actual} does not match next offset {expected}"
                )
            }
            Self::ByteLimitExceeded { limit, attempted } => {
                write!(
                    formatter,
                    "artifact size {attempted} exceeds byte limit {limit}"
                )
            }
            Self::ExpectedSizeExceeded {
                expected,
                attempted,
            } => {
                write!(
                    formatter,
                    "artifact size {attempted} exceeds declared size {expected}"
                )
            }
            Self::PendingLeaseLimitExceeded { limit } => {
                write!(
                    formatter,
                    "artifact pending lease limit {limit} was reached"
                )
            }
            Self::PendingByteLimitExceeded { limit, attempted } => write!(
                formatter,
                "pending artifact reservations {attempted} exceed byte limit {limit}"
            ),
            Self::SizeMismatch { expected, actual } => {
                write!(
                    formatter,
                    "artifact size {actual} does not match declared size {expected}"
                )
            }
            Self::ChecksumMismatch { expected, actual } => {
                write!(
                    formatter,
                    "artifact SHA-256 {actual} does not match expected {expected}"
                )
            }
            Self::StagingSizeMismatch { expected, actual } => write!(
                formatter,
                "artifact staging file size {actual} does not match tracked size {expected}"
            ),
            Self::RandomIdCollision => write!(formatter, "could not allocate a unique artifact id"),
            Self::LockPoisoned => write!(formatter, "artifact store lock is poisoned"),
        }
    }
}

impl std::error::Error for ArtifactError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<io::Error> for ArtifactError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

impl ArtifactStore {
    /// Create a store with conservative default finalized-artifact retention.
    ///
    /// Each upload remains capped by `max_bytes`. Finalized artifacts are kept
    /// for at most 15 minutes and share a total byte budget of four times the
    /// per-artifact limit. Use [`Self::new_with_retention`] when a caller needs
    /// tighter bounds.
    pub fn new(
        root: impl AsRef<Path>,
        max_bytes: u64,
        lease_ttl: Duration,
    ) -> Result<Self, ArtifactError> {
        let max_total_bytes = max_bytes.saturating_mul(DEFAULT_TOTAL_BYTES_MULTIPLIER);
        Self::new_with_retention(
            root,
            max_bytes,
            lease_ttl,
            DEFAULT_FINALIZED_TTL,
            max_total_bytes,
        )
    }

    /// Create a store with explicit finalized-artifact retention bounds.
    ///
    /// `max_bytes` caps one upload, while `max_total_bytes` caps the sum of all
    /// finalized files registered by this store. When finalizing would exceed
    /// that budget, least-recently-looked-up artifacts are deleted first.
    pub fn new_with_retention(
        root: impl AsRef<Path>,
        max_bytes: u64,
        lease_ttl: Duration,
        finalized_ttl: Duration,
        max_total_bytes: u64,
    ) -> Result<Self, ArtifactError> {
        Self::new_with_limits(
            root,
            max_bytes,
            lease_ttl,
            finalized_ttl,
            max_total_bytes,
            DEFAULT_MAX_PENDING_LEASES,
            max_total_bytes,
        )
    }

    /// Create a store with explicit completed- and pending-upload budgets.
    ///
    /// Pending leases reserve their declared size (or their current written
    /// size when no size was declared), so abandoned concurrent uploads cannot
    /// grow past the store-wide disk budget before finalization.
    pub fn new_with_limits(
        root: impl AsRef<Path>,
        max_bytes: u64,
        lease_ttl: Duration,
        finalized_ttl: Duration,
        max_total_bytes: u64,
        max_pending_leases: usize,
        max_pending_bytes: u64,
    ) -> Result<Self, ArtifactError> {
        if max_bytes == 0 {
            return Err(ArtifactError::InvalidConfig(
                "max_bytes must be greater than zero",
            ));
        }
        if lease_ttl.is_zero() {
            return Err(ArtifactError::InvalidConfig(
                "lease_ttl must be greater than zero",
            ));
        }
        if finalized_ttl.is_zero() {
            return Err(ArtifactError::InvalidConfig(
                "finalized_ttl must be greater than zero",
            ));
        }
        if max_total_bytes < max_bytes {
            return Err(ArtifactError::InvalidConfig(
                "max_total_bytes must be at least max_bytes",
            ));
        }
        if max_pending_leases == 0 {
            return Err(ArtifactError::InvalidConfig(
                "max_pending_leases must be greater than zero",
            ));
        }
        if max_pending_bytes < max_bytes {
            return Err(ArtifactError::InvalidConfig(
                "max_pending_bytes must be at least max_bytes",
            ));
        }

        fs::create_dir_all(root.as_ref())?;
        // Re-apply privacy even when a caller pre-created the directory with a
        // permissive umask. This directory contains screenshots and other
        // potentially sensitive binary artifacts.
        set_directory_private(root.as_ref())?;
        let root = fs::canonicalize(root.as_ref())?;
        if !root.is_dir() {
            return Err(ArtifactError::InvalidConfig(
                "artifact root must be a directory",
            ));
        }
        if Instant::now().checked_add(lease_ttl).is_none() {
            return Err(ArtifactError::InvalidConfig(
                "lease_ttl is too large for the platform clock",
            ));
        }
        if Instant::now().checked_add(finalized_ttl).is_none() {
            return Err(ArtifactError::InvalidConfig(
                "finalized_ttl is too large for the platform clock",
            ));
        }

        // The registry is intentionally process-local. Reclaim stale files in
        // the store's cryptographically-prefixed namespace, but retain files
        // younger than the longest lease/retention window: another daemon may
        // legitimately be serving the same project on a different port.
        sweep_orphaned_artifacts(&root, lease_ttl.max(finalized_ttl))?;

        Ok(Self {
            root: Arc::new(root),
            max_bytes,
            lease_ttl,
            finalized_ttl,
            max_total_bytes,
            max_pending_leases,
            max_pending_bytes,
            inner: Arc::new(Mutex::new(StoreInner::default())),
        })
    }

    pub fn root(&self) -> &Path {
        self.root.as_path()
    }

    pub fn max_bytes(&self) -> u64 {
        self.max_bytes
    }

    pub fn finalized_ttl(&self) -> Duration {
        self.finalized_ttl
    }

    pub fn max_total_bytes(&self) -> u64 {
        self.max_total_bytes
    }

    pub fn max_pending_leases(&self) -> usize {
        self.max_pending_leases
    }

    pub fn max_pending_bytes(&self) -> u64 {
        self.max_pending_bytes
    }

    /// Allocate a new upload lease and its private staging file.
    pub fn create_lease(
        &self,
        filename: &str,
        mime: Option<&str>,
        expected_size: Option<u64>,
    ) -> Result<ArtifactLease, ArtifactError> {
        let filename = sanitize_filename(filename)?;
        let mime = validate_mime(mime.unwrap_or("application/octet-stream"))?;
        if let Some(expected_size) = expected_size {
            if expected_size > self.max_bytes {
                return Err(ArtifactError::ByteLimitExceeded {
                    limit: self.max_bytes,
                    attempted: expected_size,
                });
            }
        }

        self.cleanup_expired()?;
        let mut inner = self.lock()?;
        if inner.leases.len() >= self.max_pending_leases {
            return Err(ArtifactError::PendingLeaseLimitExceeded {
                limit: self.max_pending_leases,
            });
        }
        let reserved_bytes = expected_size.unwrap_or(0);
        let pending_after = inner.pending_bytes.checked_add(reserved_bytes).ok_or(
            ArtifactError::PendingByteLimitExceeded {
                limit: self.max_pending_bytes,
                attempted: u64::MAX,
            },
        )?;
        if pending_after > self.max_pending_bytes {
            return Err(ArtifactError::PendingByteLimitExceeded {
                limit: self.max_pending_bytes,
                attempted: pending_after,
            });
        }
        let created_at_unix_ms = unix_time_ms(SystemTime::now());
        let expires_at_unix_ms = created_at_unix_ms.saturating_add(duration_ms(self.lease_ttl));
        let expires_at =
            Instant::now()
                .checked_add(self.lease_ttl)
                .ok_or(ArtifactError::InvalidConfig(
                    "lease_ttl is too large for the platform clock",
                ))?;

        for _ in 0..RANDOM_COLLISION_RETRIES {
            let id = random_hex(ID_RANDOM_BYTES)?;
            if inner.leases.contains_key(&id) || inner.artifacts.contains_key(&id) {
                continue;
            }

            let staging_path = self.root.join(format!(".{id}.part"));
            let final_path = self.root.join(format!("{id}-{filename}"));
            if final_path.exists() {
                continue;
            }

            match create_private_file(&staging_path) {
                Ok(file) => drop(file),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error.into()),
            }

            let token = match random_hex(TOKEN_RANDOM_BYTES) {
                Ok(token) => token,
                Err(error) => {
                    let _ = fs::remove_file(&staging_path);
                    return Err(error);
                }
            };

            inner.leases.insert(
                id.clone(),
                PendingArtifact {
                    token_hash: hash_secret(&token),
                    filename: filename.clone(),
                    mime: mime.clone(),
                    staging_path,
                    final_path,
                    expected_size,
                    reserved_bytes,
                    bytes_written: 0,
                    hasher: Sha256::new(),
                    created_at_unix_ms,
                    expires_at,
                },
            );
            inner.pending_bytes = pending_after;

            return Ok(ArtifactLease {
                id,
                token,
                filename,
                mime,
                max_bytes: self.max_bytes,
                expected_size,
                expires_at_unix_ms,
            });
        }

        Err(ArtifactError::RandomIdCollision)
    }

    /// Append one chunk at exactly `offset` bytes from the beginning.
    pub fn append(
        &self,
        id: &str,
        token: &str,
        offset: u64,
        chunk: &[u8],
    ) -> Result<AppendReceipt, ArtifactError> {
        let mut inner = self.lock()?;
        self.validate_live_lease(&mut inner, id, token)?;
        let pending_bytes_before = inner.pending_bytes;
        let (bytes_written, expected_size, reserved_bytes, staging_path) = {
            let pending = inner.leases.get(id).ok_or(ArtifactError::LeaseNotFound)?;
            (
                pending.bytes_written,
                pending.expected_size,
                pending.reserved_bytes,
                pending.staging_path.clone(),
            )
        };

        if offset != bytes_written {
            return Err(ArtifactError::OffsetMismatch {
                expected: bytes_written,
                actual: offset,
            });
        }

        let chunk_len = chunk.len() as u64;
        let attempted =
            bytes_written
                .checked_add(chunk_len)
                .ok_or(ArtifactError::ByteLimitExceeded {
                    limit: self.max_bytes,
                    attempted: u64::MAX,
                })?;
        if attempted > self.max_bytes {
            return Err(ArtifactError::ByteLimitExceeded {
                limit: self.max_bytes,
                attempted,
            });
        }
        if let Some(expected_size) = expected_size {
            if attempted > expected_size {
                return Err(ArtifactError::ExpectedSizeExceeded {
                    expected: expected_size,
                    attempted,
                });
            }
        }

        let reservation_increase = attempted.saturating_sub(reserved_bytes);
        let pending_after = pending_bytes_before
            .checked_add(reservation_increase)
            .ok_or(ArtifactError::PendingByteLimitExceeded {
                limit: self.max_pending_bytes,
                attempted: u64::MAX,
            })?;
        if pending_after > self.max_pending_bytes {
            return Err(ArtifactError::PendingByteLimitExceeded {
                limit: self.max_pending_bytes,
                attempted: pending_after,
            });
        }

        let mut file = OpenOptions::new()
            .read(true)
            .write(true)
            .open(&staging_path)?;
        let actual_size = file.metadata()?.len();
        if actual_size != bytes_written {
            return Err(ArtifactError::StagingSizeMismatch {
                expected: bytes_written,
                actual: actual_size,
            });
        }
        file.seek(SeekFrom::Start(bytes_written))?;
        if let Err(error) = file.write_all(chunk) {
            // `write_all` can fail after a partial write. Best-effort rollback
            // preserves offset/hash agreement for a retry.
            let _ = file.set_len(bytes_written);
            return Err(error.into());
        }

        let pending = inner
            .leases
            .get_mut(id)
            .ok_or(ArtifactError::LeaseNotFound)?;
        pending.hasher.update(chunk);
        pending.bytes_written = attempted;
        pending.reserved_bytes = pending.reserved_bytes.max(attempted);
        inner.pending_bytes = pending_after;
        Ok(AppendReceipt {
            id: id.to_owned(),
            offset,
            bytes_appended: chunk_len,
            total_bytes: attempted,
        })
    }

    /// Finalize a lease and return durable artifact metadata.
    ///
    /// `expected_sha256`, when supplied, must be a 64-character hexadecimal
    /// SHA-256 digest. A size or checksum failure leaves the lease active so the
    /// caller may diagnose it or abort it explicitly.
    pub fn finalize(
        &self,
        id: &str,
        token: &str,
        expected_sha256: Option<&str>,
    ) -> Result<ArtifactMetadata, ArtifactError> {
        let expected_sha256 = expected_sha256.map(normalize_sha256).transpose()?;
        let mut inner = self.lock()?;
        self.validate_live_lease(&mut inner, id, token)?;
        let (metadata, staging_path, final_path) = {
            let pending = inner.leases.get(id).ok_or(ArtifactError::LeaseNotFound)?;

            if let Some(expected_size) = pending.expected_size {
                if pending.bytes_written != expected_size {
                    return Err(ArtifactError::SizeMismatch {
                        expected: expected_size,
                        actual: pending.bytes_written,
                    });
                }
            }

            let actual_sha256 = digest_hex(pending.hasher.clone());
            if let Some(expected_sha256) = expected_sha256 {
                if !constant_time_eq(expected_sha256.as_bytes(), actual_sha256.as_bytes()) {
                    return Err(ArtifactError::ChecksumMismatch {
                        expected: expected_sha256,
                        actual: actual_sha256,
                    });
                }
            }

            let staging = OpenOptions::new()
                .read(true)
                .write(true)
                .open(&pending.staging_path)?;
            let actual_size = staging.metadata()?.len();
            if actual_size != pending.bytes_written {
                return Err(ArtifactError::StagingSizeMismatch {
                    expected: pending.bytes_written,
                    actual: actual_size,
                });
            }
            staging.sync_all()?;
            set_file_private(&pending.staging_path)?;
            drop(staging);

            (
                ArtifactMetadata {
                    id: id.to_owned(),
                    filename: pending.filename.clone(),
                    mime: pending.mime.clone(),
                    path: pending.final_path.clone(),
                    size: pending.bytes_written,
                    sha256: actual_sha256,
                    created_at_unix_ms: pending.created_at_unix_ms,
                    finalized_at_unix_ms: unix_time_ms(SystemTime::now()),
                },
                pending.staging_path.clone(),
                pending.final_path.clone(),
            )
        };

        // Reclaim expired and least-recently-used completed files before the
        // new file becomes visible. If deleting an older file fails, the live
        // upload lease remains available and the byte budget is never crossed.
        self.cleanup_finalized_locked(&mut inner, Instant::now())?;
        self.ensure_finalized_capacity_locked(&mut inner, metadata.size)?;

        // Use create-new semantics. `rename` would silently replace a file an
        // attacker created at the destination between lease creation and
        // finalization on Unix.
        fs::hard_link(&staging_path, &final_path)?;
        if let Err(error) = fs::remove_file(&staging_path) {
            let _ = fs::remove_file(&final_path);
            return Err(error.into());
        }
        if let Some(pending) = inner.leases.remove(id) {
            inner.pending_bytes = inner.pending_bytes.saturating_sub(pending.reserved_bytes);
        }
        let expires_at =
            Instant::now()
                .checked_add(self.finalized_ttl)
                .ok_or(ArtifactError::InvalidConfig(
                    "finalized_ttl is too large for the platform clock",
                ))?;
        let last_access_sequence = allocate_access_sequence(&mut inner);
        inner.finalized_bytes = inner.finalized_bytes.checked_add(metadata.size).ok_or(
            ArtifactError::InvalidConfig("finalized artifact byte accounting overflowed"),
        )?;
        inner.artifacts.insert(
            id.to_owned(),
            FinalizedArtifact {
                metadata: metadata.clone(),
                expires_at,
                last_access_sequence,
            },
        );
        Ok(metadata)
    }

    /// Cancel a live lease and remove its staging file.
    pub fn abort(&self, id: &str, token: &str) -> Result<(), ArtifactError> {
        let mut inner = self.lock()?;
        self.validate_live_lease(&mut inner, id, token)?;
        let staging_path = inner
            .leases
            .get(id)
            .map(|pending| pending.staging_path.clone())
            .ok_or(ArtifactError::LeaseNotFound)?;
        remove_if_present(&staging_path)?;
        if let Some(pending) = inner.leases.remove(id) {
            inner.pending_bytes = inner.pending_bytes.saturating_sub(pending.reserved_bytes);
        }
        Ok(())
    }

    /// Return finalized metadata and mark it as recently used.
    ///
    /// Expired artifacts are deleted before the lookup. A successful lookup
    /// protects the artifact from capacity-driven eviction until older entries
    /// have been reclaimed.
    pub fn lookup(&self, id: &str) -> Result<Option<ArtifactMetadata>, ArtifactError> {
        let mut inner = self.lock()?;
        self.cleanup_finalized_locked(&mut inner, Instant::now())?;
        if !inner.artifacts.contains_key(id) {
            return Ok(None);
        }
        let last_access_sequence = allocate_access_sequence(&mut inner);
        let artifact = inner
            .artifacts
            .get_mut(id)
            .expect("artifact existence checked while holding the store lock");
        artifact.last_access_sequence = last_access_sequence;
        Ok(Some(artifact.metadata.clone()))
    }

    /// Delete a finalized artifact and return its former metadata.
    ///
    /// A CLI should copy/read the path returned by [`Self::lookup`] and then
    /// call `consume` once that copy succeeds. Registry removal happens only
    /// after file deletion succeeds, so a transient I/O error can be retried.
    pub fn consume(&self, id: &str) -> Result<Option<ArtifactMetadata>, ArtifactError> {
        let mut inner = self.lock()?;
        self.cleanup_finalized_locked(&mut inner, Instant::now())?;
        self.remove_finalized_locked(&mut inner, id)
    }

    /// Remove expired leases and finalized artifacts with their files.
    ///
    /// Returns the total number of registry entries successfully cleaned up.
    pub fn cleanup_expired(&self) -> Result<usize, ArtifactError> {
        let mut inner = self.lock()?;
        let now = Instant::now();
        let expired: Vec<String> = inner
            .leases
            .iter()
            .filter(|(_, pending)| pending.expires_at <= now)
            .map(|(id, _)| id.clone())
            .collect();

        let mut removed = 0;
        let mut first_error = None;
        for id in expired {
            let path = inner
                .leases
                .get(&id)
                .map(|pending| pending.staging_path.clone());
            let Some(path) = path else {
                continue;
            };
            match remove_if_present(&path) {
                Ok(()) => {
                    if let Some(pending) = inner.leases.remove(&id) {
                        inner.pending_bytes =
                            inner.pending_bytes.saturating_sub(pending.reserved_bytes);
                    }
                    removed += 1;
                }
                Err(ArtifactError::Io(error)) => {
                    if first_error.is_none() {
                        first_error = Some(error);
                    }
                }
                Err(error) => return Err(error),
            }
        }

        match first_error {
            Some(error) => Err(ArtifactError::Io(error)),
            None => {
                removed += self.cleanup_finalized_locked(&mut inner, now)?;
                removed += sweep_orphaned_artifacts(
                    self.root.as_path(),
                    self.lease_ttl.max(self.finalized_ttl),
                )?;
                Ok(removed)
            }
        }
    }

    fn cleanup_finalized_locked(
        &self,
        inner: &mut StoreInner,
        now: Instant,
    ) -> Result<usize, ArtifactError> {
        let expired: Vec<String> = inner
            .artifacts
            .iter()
            .filter(|(_, artifact)| artifact.expires_at <= now)
            .map(|(id, _)| id.clone())
            .collect();

        let mut removed = 0;
        for id in expired {
            if self.remove_finalized_locked(inner, &id)?.is_some() {
                removed += 1;
            }
        }
        Ok(removed)
    }

    fn ensure_finalized_capacity_locked(
        &self,
        inner: &mut StoreInner,
        incoming_bytes: u64,
    ) -> Result<(), ArtifactError> {
        while inner
            .finalized_bytes
            .checked_add(incoming_bytes)
            .is_none_or(|total| total > self.max_total_bytes)
        {
            let least_recent_id = inner
                .artifacts
                .iter()
                .min_by(|(left_id, left), (right_id, right)| {
                    left.last_access_sequence
                        .cmp(&right.last_access_sequence)
                        .then_with(|| left_id.cmp(right_id))
                })
                .map(|(id, _)| id.clone())
                .ok_or(ArtifactError::InvalidConfig(
                    "incoming artifact exceeds finalized byte budget",
                ))?;
            self.remove_finalized_locked(inner, &least_recent_id)?;
        }
        Ok(())
    }

    fn remove_finalized_locked(
        &self,
        inner: &mut StoreInner,
        id: &str,
    ) -> Result<Option<ArtifactMetadata>, ArtifactError> {
        let Some(artifact) = inner.artifacts.get(id) else {
            return Ok(None);
        };
        remove_if_present(&artifact.metadata.path)?;
        let artifact = inner
            .artifacts
            .remove(id)
            .expect("artifact was present while holding the store lock");
        inner.finalized_bytes = inner.finalized_bytes.saturating_sub(artifact.metadata.size);
        Ok(Some(artifact.metadata))
    }

    fn lock(&self) -> Result<MutexGuard<'_, StoreInner>, ArtifactError> {
        self.inner.lock().map_err(|_| ArtifactError::LockPoisoned)
    }

    fn validate_live_lease(
        &self,
        inner: &mut StoreInner,
        id: &str,
        token: &str,
    ) -> Result<(), ArtifactError> {
        let pending = inner.leases.get(id).ok_or(ArtifactError::LeaseNotFound)?;
        if !constant_time_eq(&pending.token_hash, &hash_secret(token)) {
            return Err(ArtifactError::InvalidToken);
        }
        if pending.expires_at <= Instant::now() {
            let staging_path = inner
                .leases
                .get(id)
                .map(|pending| pending.staging_path.clone())
                .ok_or(ArtifactError::LeaseNotFound)?;
            remove_if_present(&staging_path)?;
            if let Some(pending) = inner.leases.remove(id) {
                inner.pending_bytes = inner.pending_bytes.saturating_sub(pending.reserved_bytes);
            }
            return Err(ArtifactError::LeaseExpired);
        }
        Ok(())
    }
}

/// Convert an untrusted display name to a single safe filename.
///
/// Directory separators and NUL are rejected rather than normalized. Other
/// unsupported characters become `_`, and an initial dot is prefixed so the
/// finalized artifact cannot become a hidden traversal-like name.
pub fn sanitize_filename(input: &str) -> Result<String, ArtifactError> {
    let input = input.trim();
    if input.is_empty()
        || input == "."
        || input == ".."
        || input.contains('/')
        || input.contains('\\')
        || input.contains('\0')
    {
        return Err(ArtifactError::InvalidFilename(input.to_owned()));
    }

    let mut safe = String::with_capacity(input.len().min(MAX_SAFE_FILENAME_BYTES));
    let mut previous_was_underscore = false;
    for character in input.chars() {
        let character = if character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_')
        {
            character
        } else {
            '_'
        };
        if character == '_' && previous_was_underscore {
            continue;
        }
        if safe.len() + character.len_utf8() > MAX_SAFE_FILENAME_BYTES {
            break;
        }
        previous_was_underscore = character == '_';
        safe.push(character);
    }

    if safe.is_empty() || safe == "." || safe == ".." {
        return Err(ArtifactError::InvalidFilename(input.to_owned()));
    }
    if safe.starts_with('.') {
        safe.insert_str(0, "artifact");
        safe.truncate(MAX_SAFE_FILENAME_BYTES);
    }
    Ok(safe)
}

fn sweep_orphaned_artifacts(root: &Path, minimum_age: Duration) -> Result<usize, ArtifactError> {
    let mut removed = 0;
    let now = SystemTime::now();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
            continue;
        };
        if !is_owned_artifact_filename(&name) {
            continue;
        }
        let file_type = entry.file_type()?;
        if !file_type.is_file() && !file_type.is_symlink() {
            continue;
        }
        if file_type.is_file() {
            set_file_private(&entry.path())?;
        }
        let is_stale = entry
            .metadata()
            .and_then(|metadata| metadata.modified())
            .ok()
            .and_then(|modified| now.duration_since(modified).ok())
            .is_some_and(|age| age >= minimum_age);
        if !is_stale {
            continue;
        }
        remove_if_present(&entry.path())?;
        removed += 1;
    }
    Ok(removed)
}

fn is_owned_artifact_filename(name: &str) -> bool {
    let (id, suffix) = if let Some(rest) = name.strip_prefix('.') {
        let Some(id) = rest.strip_suffix(".part") else {
            return false;
        };
        (id, None)
    } else {
        let Some((id, filename)) = name.split_once('-') else {
            return false;
        };
        (id, Some(filename))
    };

    id.len() == ID_RANDOM_BYTES * 2
        && id.bytes().all(|byte| byte.is_ascii_hexdigit())
        && suffix.is_none_or(|filename| !filename.is_empty())
}

fn validate_mime(input: &str) -> Result<String, ArtifactError> {
    let value = input.trim();
    if value.is_empty()
        || value.len() > MAX_MIME_BYTES
        || value.chars().any(char::is_control)
        || !value.contains('/')
    {
        return Err(ArtifactError::InvalidMime);
    }
    Ok(value.to_owned())
}

fn normalize_sha256(input: &str) -> Result<String, ArtifactError> {
    if input.len() != 64 || !input.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(ArtifactError::InvalidChecksum);
    }
    Ok(input.to_ascii_lowercase())
}

fn hash_secret(secret: &str) -> [u8; 32] {
    Sha256::digest(secret.as_bytes()).into()
}

fn digest_hex(hasher: Sha256) -> String {
    bytes_to_hex(&hasher.finalize())
}

fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {
    if left.len() != right.len() {
        return false;
    }
    let mut difference = 0_u8;
    for (&left, &right) in left.iter().zip(right) {
        difference |= left ^ right;
    }
    difference == 0
}

fn allocate_access_sequence(inner: &mut StoreInner) -> u64 {
    if inner.next_access_sequence == u64::MAX {
        // This is practically unreachable, but renumbering preserves LRU order
        // instead of allowing a wrapping counter to make new artifacts oldest.
        let mut ordered: Vec<(String, u64)> = inner
            .artifacts
            .iter()
            .map(|(id, artifact)| (id.clone(), artifact.last_access_sequence))
            .collect();
        ordered.sort_by(|(left_id, left), (right_id, right)| {
            left.cmp(right).then_with(|| left_id.cmp(right_id))
        });
        for (sequence, (id, _)) in ordered.into_iter().enumerate() {
            if let Some(artifact) = inner.artifacts.get_mut(&id) {
                artifact.last_access_sequence = sequence as u64;
            }
        }
        inner.next_access_sequence = inner.artifacts.len() as u64;
    }

    let sequence = inner.next_access_sequence;
    inner.next_access_sequence += 1;
    sequence
}

fn duration_ms(duration: Duration) -> u64 {
    duration.as_millis().min(u128::from(u64::MAX)) as u64
}

fn unix_time_ms(time: SystemTime) -> u64 {
    time.duration_since(UNIX_EPOCH)
        .map(duration_ms)
        .unwrap_or(0)
}

pub(crate) fn random_hex(byte_count: usize) -> Result<String, ArtifactError> {
    let mut bytes = vec![0_u8; byte_count];
    fill_secure_random(&mut bytes)?;
    Ok(bytes_to_hex(&bytes))
}

fn bytes_to_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(char::from(HEX[(byte >> 4) as usize]));
        encoded.push(char::from(HEX[(byte & 0x0f) as usize]));
    }
    encoded
}

#[cfg(unix)]
fn fill_secure_random(bytes: &mut [u8]) -> Result<(), ArtifactError> {
    use std::io::Read as _;

    File::open("/dev/urandom")?.read_exact(bytes)?;
    Ok(())
}

#[cfg(windows)]
fn fill_secure_random(bytes: &mut [u8]) -> Result<(), ArtifactError> {
    use std::ffi::c_void;

    #[link(name = "bcrypt")]
    extern "system" {
        fn BCryptGenRandom(
            algorithm: *mut c_void,
            buffer: *mut u8,
            buffer_len: u32,
            flags: u32,
        ) -> i32;
    }

    const BCRYPT_USE_SYSTEM_PREFERRED_RNG: u32 = 0x0000_0002;
    let length = u32::try_from(bytes.len()).map_err(|_| {
        ArtifactError::Io(io::Error::new(
            io::ErrorKind::InvalidInput,
            "secure random request is too large",
        ))
    })?;
    // SAFETY: BCryptGenRandom receives a valid writable buffer for exactly
    // `length` bytes, and a null algorithm handle is required with the system
    // preferred RNG flag.
    let status = unsafe {
        BCryptGenRandom(
            std::ptr::null_mut(),
            bytes.as_mut_ptr(),
            length,
            BCRYPT_USE_SYSTEM_PREFERRED_RNG,
        )
    };
    if status != 0 {
        return Err(ArtifactError::Io(io::Error::other(format!(
            "BCryptGenRandom failed with NTSTATUS {status:#x}"
        ))));
    }
    Ok(())
}

#[cfg(not(any(unix, windows)))]
fn fill_secure_random(_bytes: &mut [u8]) -> Result<(), ArtifactError> {
    Err(ArtifactError::Io(io::Error::new(
        io::ErrorKind::Unsupported,
        "no operating-system CSPRNG implementation for this platform",
    )))
}

fn create_private_file(path: &Path) -> io::Result<File> {
    let mut options = OpenOptions::new();
    options.create_new(true).read(true).write(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let file = options.open(path)?;
    if let Err(error) = set_file_private(path) {
        drop(file);
        let _ = fs::remove_file(path);
        return Err(error);
    }
    Ok(file)
}

#[cfg(unix)]
fn set_file_private(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
}

#[cfg(windows)]
fn set_file_private(path: &Path) -> io::Result<()> {
    set_windows_owner_only_acl(path, false)
}

#[cfg(unix)]
fn set_directory_private(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))
}

#[cfg(windows)]
fn set_directory_private(path: &Path) -> io::Result<()> {
    set_windows_owner_only_acl(path, true)
}

#[cfg(not(any(unix, windows)))]
fn set_file_private(_path: &Path) -> io::Result<()> {
    Ok(())
}

#[cfg(not(any(unix, windows)))]
fn set_directory_private(_path: &Path) -> io::Result<()> {
    Ok(())
}

/// Replace inherited Windows permissions with a protected DACL granting full
/// access only to the user running the daemon. Directory ACEs inherit to both
/// child files and subdirectories; each staging/final file is hardened again
/// after creation as defense in depth.
#[cfg(windows)]
fn set_windows_owner_only_acl(path: &Path, inherit_to_children: bool) -> io::Result<()> {
    use std::ffi::c_void;
    use std::os::windows::ffi::OsStrExt as _;
    use std::ptr;

    type Handle = *mut c_void;

    #[repr(C)]
    #[allow(non_snake_case)]
    struct SidAndAttributes {
        Sid: *mut c_void,
        Attributes: u32,
    }

    #[repr(C)]
    #[allow(non_snake_case)]
    struct TokenUser {
        User: SidAndAttributes,
    }

    #[repr(C)]
    #[allow(non_snake_case)]
    struct TrusteeW {
        pMultipleTrustee: *mut TrusteeW,
        MultipleTrusteeOperation: u32,
        TrusteeForm: u32,
        TrusteeType: u32,
        ptstrName: *mut u16,
    }

    #[repr(C)]
    #[allow(non_snake_case)]
    struct ExplicitAccessW {
        grfAccessPermissions: u32,
        grfAccessMode: u32,
        grfInheritance: u32,
        Trustee: TrusteeW,
    }

    #[link(name = "kernel32")]
    extern "system" {
        fn GetCurrentProcess() -> Handle;
        fn CloseHandle(handle: Handle) -> i32;
        fn LocalFree(memory: *mut c_void) -> *mut c_void;
    }
    #[link(name = "advapi32")]
    extern "system" {
        fn OpenProcessToken(process: Handle, desired_access: u32, token: *mut Handle) -> i32;
        fn GetTokenInformation(
            token: Handle,
            information_class: u32,
            information: *mut c_void,
            information_len: u32,
            return_len: *mut u32,
        ) -> i32;
        fn SetEntriesInAclW(
            count: u32,
            entries: *mut ExplicitAccessW,
            old_acl: *mut c_void,
            new_acl: *mut *mut c_void,
        ) -> u32;
        fn SetNamedSecurityInfoW(
            object_name: *mut u16,
            object_type: u32,
            security_info: u32,
            owner: *mut c_void,
            group: *mut c_void,
            dacl: *mut c_void,
            sacl: *mut c_void,
        ) -> u32;
    }

    const TOKEN_QUERY: u32 = 0x0008;
    const TOKEN_USER_CLASS: u32 = 1;
    const FILE_ALL_ACCESS: u32 = 0x001f_01ff;
    const SET_ACCESS: u32 = 2;
    const TRUSTEE_IS_SID: u32 = 0;
    const TRUSTEE_IS_USER: u32 = 1;
    const SUB_CONTAINERS_AND_OBJECTS_INHERIT: u32 = 0x3;
    const SE_FILE_OBJECT: u32 = 1;
    const DACL_SECURITY_INFORMATION: u32 = 0x0000_0004;
    const PROTECTED_DACL_SECURITY_INFORMATION: u32 = 0x8000_0000;

    struct OwnedHandle(Handle);
    impl Drop for OwnedHandle {
        fn drop(&mut self) {
            // SAFETY: this wrapper is constructed only from a successful
            // OpenProcessToken call and owns exactly one Windows handle.
            unsafe {
                CloseHandle(self.0);
            }
        }
    }

    struct LocalAllocation(*mut c_void);
    impl Drop for LocalAllocation {
        fn drop(&mut self) {
            if !self.0.is_null() {
                // SAFETY: SetEntriesInAclW returns memory owned by LocalFree.
                unsafe {
                    LocalFree(self.0);
                }
            }
        }
    }

    let mut raw_token = ptr::null_mut();
    // SAFETY: all output pointers are valid, and the pseudo process handle is
    // valid for the duration of this call.
    if unsafe { OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &mut raw_token) } == 0 {
        return Err(io::Error::last_os_error());
    }
    let token = OwnedHandle(raw_token);

    let mut needed = 0_u32;
    // The first call intentionally supplies no buffer to discover its size.
    unsafe {
        GetTokenInformation(token.0, TOKEN_USER_CLASS, ptr::null_mut(), 0, &mut needed);
    }
    if needed < std::mem::size_of::<TokenUser>() as u32 {
        return Err(io::Error::last_os_error());
    }
    let word_count = (needed as usize).div_ceil(std::mem::size_of::<usize>());
    let mut token_buffer = vec![0_usize; word_count];
    // SAFETY: token_buffer is aligned and has at least `needed` writable bytes.
    if unsafe {
        GetTokenInformation(
            token.0,
            TOKEN_USER_CLASS,
            token_buffer.as_mut_ptr().cast(),
            needed,
            &mut needed,
        )
    } == 0
    {
        return Err(io::Error::last_os_error());
    }
    // SAFETY: TOKEN_USER_CLASS guarantees the returned buffer begins with a
    // TOKEN_USER structure whose SID remains alive with token_buffer.
    let user_sid = unsafe { (*(token_buffer.as_ptr().cast::<TokenUser>())).User.Sid };
    if user_sid.is_null() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "Windows access token did not contain a user SID",
        ));
    }

    let mut entry = ExplicitAccessW {
        grfAccessPermissions: FILE_ALL_ACCESS,
        grfAccessMode: SET_ACCESS,
        grfInheritance: if inherit_to_children {
            SUB_CONTAINERS_AND_OBJECTS_INHERIT
        } else {
            0
        },
        Trustee: TrusteeW {
            pMultipleTrustee: ptr::null_mut(),
            MultipleTrusteeOperation: 0,
            TrusteeForm: TRUSTEE_IS_SID,
            TrusteeType: TRUSTEE_IS_USER,
            ptstrName: user_sid.cast(),
        },
    };
    let mut raw_acl = ptr::null_mut();
    // SAFETY: entry references a live SID and raw_acl is a valid out pointer.
    let acl_status = unsafe { SetEntriesInAclW(1, &mut entry, ptr::null_mut(), &mut raw_acl) };
    if acl_status != 0 {
        return Err(io::Error::from_raw_os_error(acl_status as i32));
    }
    let acl = LocalAllocation(raw_acl);

    let mut wide_path: Vec<u16> = path.as_os_str().encode_wide().chain(Some(0)).collect();
    // SAFETY: wide_path is NUL-terminated and writable; the ACL allocation and
    // its referenced SID remain alive through the call.
    let security_status = unsafe {
        SetNamedSecurityInfoW(
            wide_path.as_mut_ptr(),
            SE_FILE_OBJECT,
            DACL_SECURITY_INFORMATION | PROTECTED_DACL_SECURITY_INFORMATION,
            ptr::null_mut(),
            ptr::null_mut(),
            acl.0,
            ptr::null_mut(),
        )
    };
    if security_status != 0 {
        return Err(io::Error::from_raw_os_error(security_status as i32));
    }
    Ok(())
}

fn remove_if_present(path: &Path) -> Result<(), ArtifactError> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;
    use std::sync::Barrier;
    use std::thread;

    fn store(root: &Path, max_bytes: u64) -> ArtifactStore {
        ArtifactStore::new(root, max_bytes, Duration::from_secs(30)).unwrap()
    }

    #[test]
    fn lease_append_finalize_lookup_and_consume() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(&temp.path().join("artifacts"), 1024);
        let lease = store
            .create_lease("screen shot.png", Some("image/png"), Some(6))
            .unwrap();
        assert_eq!(lease.filename, "screen_shot.png");
        assert_eq!(lease.id.len(), ID_RANDOM_BYTES * 2);
        assert_eq!(lease.token.len(), TOKEN_RANDOM_BYTES * 2);

        let first = store.append(&lease.id, &lease.token, 0, b"abc").unwrap();
        assert_eq!(first.total_bytes, 3);
        let second = store.append(&lease.id, &lease.token, 3, b"def").unwrap();
        assert_eq!(second.total_bytes, 6);

        let metadata = store
            .finalize(
                &lease.id,
                &lease.token,
                Some("bef57ec7f53a6d40beb640a780a639c83bc29ac8a9816f1fc6c5c6dcd93c4721"),
            )
            .unwrap();
        assert_eq!(metadata.size, 6);
        assert_eq!(fs::read(&metadata.path).unwrap(), b"abcdef");
        assert!(metadata.path.starts_with(store.root()));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(&metadata.path).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }

        assert_eq!(store.lookup(&lease.id).unwrap(), Some(metadata.clone()));
        let finalized_path = metadata.path.clone();
        assert_eq!(store.consume(&lease.id).unwrap(), Some(metadata));
        assert!(!finalized_path.exists());
        assert_eq!(store.lookup(&lease.id).unwrap(), None);
    }

    #[test]
    fn leases_have_unique_csprng_ids_and_tokens() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(temp.path(), 1);
        let mut ids = HashSet::new();
        let mut tokens = HashSet::new();
        for index in 0..64 {
            let lease = store
                .create_lease(&format!("artifact-{index}.bin"), None, None)
                .unwrap();
            assert!(ids.insert(lease.id.clone()));
            assert!(tokens.insert(lease.token.clone()));
            store.abort(&lease.id, &lease.token).unwrap();
        }
    }

    #[test]
    fn pending_lease_and_byte_budgets_are_enforced_and_reclaimed() {
        let temp = tempfile::tempdir().unwrap();
        let store = ArtifactStore::new_with_limits(
            temp.path(),
            8,
            Duration::from_secs(30),
            Duration::from_secs(30),
            16,
            2,
            8,
        )
        .unwrap();

        let reserved = store.create_lease("reserved.bin", None, Some(6)).unwrap();
        let streaming = store.create_lease("streaming.bin", None, None).unwrap();
        assert!(matches!(
            store.create_lease("third.bin", None, None),
            Err(ArtifactError::PendingLeaseLimitExceeded { limit: 2 })
        ));
        store
            .append(&streaming.id, &streaming.token, 0, b"12")
            .unwrap();
        assert!(matches!(
            store.append(&streaming.id, &streaming.token, 2, b"3"),
            Err(ArtifactError::PendingByteLimitExceeded {
                limit: 8,
                attempted: 9
            })
        ));
        assert_eq!(store.lock().unwrap().pending_bytes, 8);

        store.abort(&reserved.id, &reserved.token).unwrap();
        store
            .append(&streaming.id, &streaming.token, 2, b"345678")
            .unwrap();
        assert_eq!(store.lock().unwrap().pending_bytes, 8);
        store
            .finalize(&streaming.id, &streaming.token, None)
            .unwrap();
        assert_eq!(store.lock().unwrap().pending_bytes, 0);
    }

    #[test]
    fn startup_sweeps_only_owned_orphan_names_and_reapplies_private_mode() {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("artifacts");
        fs::create_dir(&root).unwrap();
        let id = "a".repeat(ID_RANDOM_BYTES * 2);
        let partial = root.join(format!(".{id}.part"));
        let finalized = root.join(format!("{id}-capture.png"));
        let unrelated = root.join("keep-me.txt");
        fs::write(&partial, b"partial").unwrap();
        fs::write(&finalized, b"final").unwrap();
        fs::write(&unrelated, b"unrelated").unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&root, fs::Permissions::from_mode(0o777)).unwrap();
        }

        thread::sleep(Duration::from_millis(20));
        let store = ArtifactStore::new_with_retention(
            &root,
            8,
            Duration::from_millis(1),
            Duration::from_millis(1),
            32,
        )
        .unwrap();
        let _ = &store;
        assert!(!partial.exists());
        assert!(!finalized.exists());
        assert_eq!(fs::read(unrelated).unwrap(), b"unrelated");

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(store.root()).unwrap().permissions().mode() & 0o777,
                0o700
            );
        }
    }

    #[test]
    fn second_store_does_not_sweep_another_live_stores_artifacts() {
        let temp = tempfile::tempdir().unwrap();
        let first = ArtifactStore::new_with_retention(
            temp.path(),
            8,
            Duration::from_secs(30),
            Duration::from_secs(30),
            32,
        )
        .unwrap();
        let pending = first.create_lease("pending.bin", None, Some(1)).unwrap();
        first.append(&pending.id, &pending.token, 0, b"x").unwrap();
        let pending_path = first.root().join(format!(".{}.part", pending.id));

        let finalized_lease = first.create_lease("finalized.bin", None, Some(1)).unwrap();
        first
            .append(&finalized_lease.id, &finalized_lease.token, 0, b"y")
            .unwrap();
        let finalized = first
            .finalize(&finalized_lease.id, &finalized_lease.token, None)
            .unwrap();

        let _second = ArtifactStore::new_with_retention(
            temp.path(),
            8,
            Duration::from_secs(30),
            Duration::from_secs(30),
            32,
        )
        .unwrap();
        assert!(pending_path.exists());
        assert!(finalized.path.exists());
        first.abort(&pending.id, &pending.token).unwrap();
        first.consume(&finalized_lease.id).unwrap();
    }

    #[test]
    fn token_is_redacted_and_cannot_be_reused_after_finalize() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(temp.path(), 8);
        let lease = store.create_lease("x.bin", None, Some(1)).unwrap();
        assert!(!format!("{lease:?}").contains(&lease.token));
        assert!(matches!(
            store.append(&lease.id, "wrong", 0, b"x"),
            Err(ArtifactError::InvalidToken)
        ));

        store.append(&lease.id, &lease.token, 0, b"x").unwrap();
        store.finalize(&lease.id, &lease.token, None).unwrap();
        assert!(matches!(
            store.append(&lease.id, &lease.token, 1, b"y"),
            Err(ArtifactError::LeaseNotFound)
        ));
        assert!(matches!(
            store.finalize(&lease.id, &lease.token, None),
            Err(ArtifactError::LeaseNotFound)
        ));
    }

    #[test]
    fn validates_offsets_and_all_size_limits_before_writing() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(temp.path(), 4);
        assert!(matches!(
            store.create_lease("large.bin", None, Some(5)),
            Err(ArtifactError::ByteLimitExceeded { .. })
        ));

        let lease = store.create_lease("small.bin", None, Some(3)).unwrap();
        assert!(matches!(
            store.append(&lease.id, &lease.token, 1, b"a"),
            Err(ArtifactError::OffsetMismatch { .. })
        ));
        assert!(matches!(
            store.append(&lease.id, &lease.token, 0, b"abcd"),
            Err(ArtifactError::ExpectedSizeExceeded { .. })
        ));
        store.append(&lease.id, &lease.token, 0, b"ab").unwrap();
        assert!(matches!(
            store.finalize(&lease.id, &lease.token, None),
            Err(ArtifactError::SizeMismatch { .. })
        ));

        let capped = store.create_lease("capped.bin", None, None).unwrap();
        assert!(matches!(
            store.append(&capped.id, &capped.token, 0, b"abcde"),
            Err(ArtifactError::ByteLimitExceeded { .. })
        ));
    }

    #[test]
    fn checksum_failure_keeps_lease_available() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(temp.path(), 8);
        let lease = store.create_lease("x.bin", None, Some(1)).unwrap();
        store.append(&lease.id, &lease.token, 0, b"x").unwrap();
        assert!(matches!(
            store.finalize(
                &lease.id,
                &lease.token,
                Some("0000000000000000000000000000000000000000000000000000000000000000")
            ),
            Err(ArtifactError::ChecksumMismatch { .. })
        ));
        assert!(store.finalize(&lease.id, &lease.token, None).is_ok());
    }

    #[test]
    fn cleanup_removes_expired_partial_files() {
        let temp = tempfile::tempdir().unwrap();
        let store = ArtifactStore::new(temp.path(), 8, Duration::from_millis(20)).unwrap();
        let lease = store.create_lease("x.bin", None, None).unwrap();
        store.append(&lease.id, &lease.token, 0, b"x").unwrap();
        let partial = store.root().join(format!(".{}.part", lease.id));
        assert!(partial.exists());

        thread::sleep(Duration::from_millis(80));
        assert_eq!(store.cleanup_expired().unwrap(), 1);
        assert!(!partial.exists());
        assert!(matches!(
            store.append(&lease.id, &lease.token, 1, b"x"),
            Err(ArtifactError::LeaseNotFound)
        ));
    }

    #[test]
    fn cleanup_removes_expired_finalized_files_and_registry_entries() {
        let temp = tempfile::tempdir().unwrap();
        let store = ArtifactStore::new_with_retention(
            temp.path(),
            8,
            Duration::from_secs(30),
            Duration::from_millis(20),
            16,
        )
        .unwrap();
        let lease = store.create_lease("x.bin", None, Some(1)).unwrap();
        store.append(&lease.id, &lease.token, 0, b"x").unwrap();
        let metadata = store.finalize(&lease.id, &lease.token, None).unwrap();
        assert!(metadata.path.exists());

        thread::sleep(Duration::from_millis(80));
        assert_eq!(store.cleanup_expired().unwrap(), 1);
        assert!(!metadata.path.exists());
        assert_eq!(store.lookup(&lease.id).unwrap(), None);
        assert_eq!(store.lock().unwrap().finalized_bytes, 0);
    }

    #[test]
    fn lookup_enforces_finalized_ttl_without_explicit_cleanup() {
        let temp = tempfile::tempdir().unwrap();
        let store = ArtifactStore::new_with_retention(
            temp.path(),
            8,
            Duration::from_secs(30),
            Duration::from_millis(20),
            16,
        )
        .unwrap();
        let lease = store.create_lease("x.bin", None, Some(1)).unwrap();
        store.append(&lease.id, &lease.token, 0, b"x").unwrap();
        let metadata = store.finalize(&lease.id, &lease.token, None).unwrap();

        thread::sleep(Duration::from_millis(80));
        assert_eq!(store.lookup(&lease.id).unwrap(), None);
        assert!(!metadata.path.exists());
    }

    #[test]
    fn total_byte_budget_evicts_the_least_recently_used_artifact() {
        let temp = tempfile::tempdir().unwrap();
        let store = ArtifactStore::new_with_retention(
            temp.path(),
            4,
            Duration::from_secs(30),
            Duration::from_secs(30),
            8,
        )
        .unwrap();

        let finalize = |name: &str, bytes: &[u8]| {
            let lease = store
                .create_lease(name, None, Some(bytes.len() as u64))
                .unwrap();
            store.append(&lease.id, &lease.token, 0, bytes).unwrap();
            let metadata = store.finalize(&lease.id, &lease.token, None).unwrap();
            (lease.id, metadata)
        };

        let (first_id, first) = finalize("first.bin", b"1111");
        let (second_id, second) = finalize("second.bin", b"2222");
        // Refresh the first artifact, making the second the LRU entry.
        assert!(store.lookup(&first_id).unwrap().is_some());
        let (third_id, third) = finalize("third.bin", b"3333");

        assert!(first.path.exists());
        assert!(!second.path.exists());
        assert!(third.path.exists());
        assert!(store.lookup(&first_id).unwrap().is_some());
        assert_eq!(store.lookup(&second_id).unwrap(), None);
        assert!(store.lookup(&third_id).unwrap().is_some());
        assert_eq!(store.lock().unwrap().finalized_bytes, 8);
    }

    #[test]
    fn retention_configuration_requires_room_for_one_maximum_artifact() {
        let temp = tempfile::tempdir().unwrap();
        assert!(matches!(
            ArtifactStore::new_with_retention(
                temp.path(),
                8,
                Duration::from_secs(1),
                Duration::from_secs(1),
                7,
            ),
            Err(ArtifactError::InvalidConfig(_))
        ));
    }

    #[test]
    fn concurrent_same_offset_append_has_one_winner() {
        let temp = tempfile::tempdir().unwrap();
        let store = store(temp.path(), 8);
        let lease = store.create_lease("x.bin", None, Some(1)).unwrap();
        let barrier = Arc::new(Barrier::new(3));

        let mut threads = Vec::new();
        for byte in *b"ab" {
            let store = store.clone();
            let lease = lease.clone();
            let barrier = barrier.clone();
            threads.push(thread::spawn(move || {
                barrier.wait();
                store.append(&lease.id, &lease.token, 0, &[byte])
            }));
        }
        barrier.wait();
        let results: Vec<_> = threads
            .into_iter()
            .map(|thread| thread.join().unwrap())
            .collect();
        assert_eq!(results.iter().filter(|result| result.is_ok()).count(), 1);
        assert_eq!(
            results
                .iter()
                .filter(|result| matches!(result, Err(ArtifactError::OffsetMismatch { .. })))
                .count(),
            1
        );
    }

    #[test]
    fn filenames_cannot_escape_the_artifact_root() {
        for unsafe_name in ["", ".", "..", "../x", "a/b", "a\\b", "x\0png"] {
            assert!(matches!(
                sanitize_filename(unsafe_name),
                Err(ArtifactError::InvalidFilename(_))
            ));
        }
        assert_eq!(
            sanitize_filename(" hello: world.png ").unwrap(),
            "hello_world.png"
        );
        assert_eq!(sanitize_filename(".hidden").unwrap(), "artifact.hidden");
    }
}
