//! `rosync path` — translate between Studio instance paths and Ro-Sync files.

use crate::fs_map::{
    classify_script_file, decode_name, encode_name, instance_to_path, is_init_file,
    parse_disambiguated, path_to_instance_meta, InstanceDescriptor, META_FILE,
};
use crate::snapshot::{SYNCED_SERVICES, TREE_JSON};
use clap::ValueEnum;
use serde_json::Value;
use std::collections::HashSet;
use std::path::{Component, Path, PathBuf};

const SYNCED_CLASSES: &[&str] = &["Folder", "Script", "LocalScript", "ModuleScript"];

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum PathInputKind {
    /// Try Studio path first, then filesystem path.
    Auto,
    /// Interpret the input as a Studio instance path and print its filesystem path.
    Studio,
    /// Interpret the input as a filesystem path and print its Studio instance path.
    Fs,
}

impl PathInputKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Auto => "auto",
            Self::Studio => "studio",
            Self::Fs => "fs",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ResolvedPath {
    pub input_kind: PathInputKind,
    pub studio_path: Vec<String>,
    pub class: String,
    pub fs_path: PathBuf,
    pub fs_exists: bool,
}

impl ResolvedPath {
    pub fn studio_path_string(&self) -> String {
        self.studio_path.join("/")
    }
}

pub fn resolve(project: &Path, input: &str, from: PathInputKind) -> Result<ResolvedPath, String> {
    let project = absolute_lexical(project)?;
    let tree = load_tree(&project)?;

    match from {
        PathInputKind::Studio => studio_to_fs(&project, &tree, input, PathInputKind::Studio),
        PathInputKind::Fs => fs_to_studio(&project, &tree, input, PathInputKind::Fs),
        PathInputKind::Auto => {
            if looks_like_studio_path(&tree, input) {
                studio_to_fs(&project, &tree, input, PathInputKind::Studio)
            } else {
                fs_to_studio(&project, &tree, input, PathInputKind::Fs)
            }
        }
    }
}

fn load_tree(project: &Path) -> Result<Value, String> {
    let tree_path = project.join(TREE_JSON);
    let text = match std::fs::read_to_string(&tree_path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(format!(
                "path: no tree.json at {}. Connect Studio via the Ro Sync plugin to generate it.",
                tree_path.display()
            ));
        }
        Err(e) => return Err(format!("path: read {}: {e}", tree_path.display())),
    };
    serde_json::from_str(&text).map_err(|e| format!("path: parse {}: {e}", tree_path.display()))
}

fn looks_like_studio_path(tree: &Value, input: &str) -> bool {
    let Some(segs) = parse_studio_path(input).ok() else {
        return false;
    };
    !find_tree_paths(tree, &segs).is_empty()
}

fn studio_to_fs(
    project: &Path,
    tree: &Value,
    input: &str,
    input_kind: PathInputKind,
) -> Result<ResolvedPath, String> {
    let segs = parse_studio_path(input)?;
    let matches = find_tree_paths(tree, &segs);
    let nodes = one_tree_match(matches, input)?;
    validate_syncable_studio_path(&nodes, input)?;

    let mut fs_path = project.to_path_buf();
    for (idx, node) in nodes.iter().enumerate() {
        let name = node_name(node).ok_or_else(|| "path: tree node missing name".to_string())?;
        if idx == 0 {
            fs_path = fs_path.join(encode_name(name));
            continue;
        }
        let parent = nodes[idx - 1];
        let fragment = child_fragment(project, &fs_path, parent, node)?;
        fs_path = fs_path.join(fragment);
    }

    Ok(ResolvedPath {
        input_kind,
        studio_path: segs,
        class: node_class(nodes[nodes.len() - 1]).unwrap_or("").to_string(),
        fs_exists: fs_path.exists(),
        fs_path,
    })
}

fn fs_to_studio(
    project: &Path,
    tree: &Value,
    input: &str,
    input_kind: PathInputKind,
) -> Result<ResolvedPath, String> {
    let fs_path = resolve_fs_input(project, input)?;
    let rel = fs_path.strip_prefix(project).map_err(|_| {
        format!(
            "path: filesystem path {} is outside project {}",
            fs_path.display(),
            project.display()
        )
    })?;
    let components = path_components(rel)?;
    if components.is_empty() {
        return Err("path: project root is not a Studio instance path".to_string());
    }

    if is_generated_root_file(&components) {
        return Err(format!(
            "path: {} is generated by Ro-Sync and is not a syncable Studio instance",
            fs_path.display()
        ));
    }

    let service = decode_fs_stem(&components[0]);
    if !SYNCED_SERVICES.contains(&service.as_str()) {
        return Err(format!(
            "path: {} is under unsynced top-level folder {:?}; synced services are: {}",
            fs_path.display(),
            components[0],
            SYNCED_SERVICES.join(", ")
        ));
    }

    let mut studio_path = vec![service];
    let mut stopped_at_init = false;
    for (idx, component) in components.iter().enumerate().skip(1) {
        let is_last = idx + 1 == components.len();
        let cur = project.join(components[..=idx].iter().collect::<PathBuf>());

        if is_init_file(component) {
            if !is_last {
                return Err(format!(
                    "path: init file {} describes its parent instance and cannot have children",
                    cur.display()
                ));
            }
            stopped_at_init = true;
            break;
        }

        let segment = if cur.exists() {
            let Some(inst) = path_to_instance_meta(&cur)
                .map_err(|e| format!("path: inspect filesystem path {}: {e}", cur.display()))?
            else {
                return Err(format!(
                    "path: {} is not a syncable Ro-Sync file or folder",
                    cur.display()
                ));
            };
            inst.name
        } else if let Some((_, stem)) = classify_script_file(component) {
            decode_fs_stem(&stem)
        } else if component.contains('.') {
            return Err(format!(
                "path: {} is not a syncable script file (.luau/.lua, .server.*, .client.*)",
                cur.display()
            ));
        } else {
            decode_fs_stem(component)
        };
        studio_path.push(segment);
    }

    if stopped_at_init && studio_path.len() == 1 {
        return Err(format!(
            "path: init file {} has no parent instance inside a synced service",
            fs_path.display()
        ));
    }

    let matches = find_tree_paths(tree, &studio_path);
    if matches.is_empty() {
        return Err(format!(
            "path: filesystem path {} maps to likely Studio path {}, but that path is not present in tree.json",
            fs_path.display(),
            studio_path.join("/")
        ));
    }
    let nodes = one_tree_match(matches, &studio_path.join("/"))?;
    validate_syncable_studio_path(&nodes, &studio_path.join("/"))?;

    Ok(ResolvedPath {
        input_kind,
        studio_path,
        class: node_class(nodes[nodes.len() - 1]).unwrap_or("").to_string(),
        fs_exists: fs_path.exists(),
        fs_path,
    })
}

fn parse_studio_path(input: &str) -> Result<Vec<String>, String> {
    let trimmed = input.trim_matches('/');
    if trimmed.is_empty() {
        return Err("path: Studio path is empty; pass a service or descendant".to_string());
    }
    let segs: Vec<String> = trimmed.split('/').map(str::to_string).collect();
    if segs.iter().any(|s| s.is_empty()) {
        return Err(format!(
            "path: Studio path {input:?} contains an empty segment"
        ));
    }
    Ok(segs)
}

fn validate_syncable_studio_path(nodes: &[&Value], display: &str) -> Result<(), String> {
    let service = node_name(nodes[0]).unwrap_or("");
    if !SYNCED_SERVICES.contains(&service) {
        return Err(format!(
            "path: Studio path {display} is under unsynced service {service}; synced services are: {}",
            SYNCED_SERVICES.join(", ")
        ));
    }
    if nodes.len() == 1 {
        return Ok(());
    }
    let class = node_class(nodes[nodes.len() - 1]).unwrap_or("");
    if !SYNCED_CLASSES.contains(&class) {
        return Err(format!(
            "path: Studio path {display} is a {class}, which is Studio-authoritative and has no filesystem path. Syncable classes: {}",
            SYNCED_CLASSES.join(", ")
        ));
    }
    Ok(())
}

fn child_fragment(
    project: &Path,
    parent_dir: &Path,
    parent_node: &Value,
    child_node: &Value,
) -> Result<String, String> {
    let name = node_name(child_node).ok_or_else(|| "path: tree node missing name".to_string())?;
    if let Some(existing) = find_existing_child_fragment_by_name(parent_dir, name)? {
        return Ok(existing);
    }

    let mut taken = existing_fragments(parent_dir)?;
    let mut seen: HashSet<String> = taken.iter().cloned().collect();

    let Some(children) = parent_node.get("children").and_then(|v| v.as_array()) else {
        return Err(format!(
            "path: tree node {} has no children to resolve {}",
            node_name(parent_node).unwrap_or("?"),
            name
        ));
    };
    for sibling in children {
        if std::ptr::eq(sibling, child_node) {
            break;
        }
        if !is_syncable_child(sibling) {
            continue;
        }
        let Some(sibling_name) = node_name(sibling) else {
            continue;
        };
        if find_existing_child_fragment_by_name(parent_dir, sibling_name)?.is_some() {
            continue;
        }
        let fragment = instance_to_path(
            &InstanceDescriptor {
                class: node_class(sibling).unwrap_or(""),
                name: sibling_name,
                has_children: node_has_children(sibling),
            },
            &taken,
        )
        .fragment;
        if seen.insert(fragment.clone()) {
            taken.push(fragment);
        }
    }

    let fragment = instance_to_path(
        &InstanceDescriptor {
            class: node_class(child_node).unwrap_or(""),
            name,
            has_children: node_has_children(child_node),
        },
        &taken,
    );

    let path = parent_dir.join(&fragment.fragment);
    if path.starts_with(project) {
        Ok(fragment.fragment)
    } else {
        Err(format!(
            "path: resolved path escaped project: {}",
            path.display()
        ))
    }
}

fn find_existing_child_fragment_by_name(dir: &Path, name: &str) -> Result<Option<String>, String> {
    if !dir.is_dir() {
        return Ok(None);
    }
    let mut found = Vec::new();
    let iter = std::fs::read_dir(dir).map_err(|e| format!("path: read {}: {e}", dir.display()))?;
    for entry in iter {
        let entry = entry.map_err(|e| format!("path: read {}: {e}", dir.display()))?;
        let fname = entry.file_name();
        let Some(fname) = fname.to_str() else {
            continue;
        };
        if fname == META_FILE {
            continue;
        }
        if let Some(inst) = path_to_instance_meta(&entry.path())
            .map_err(|e| format!("path: inspect {}: {e}", entry.path().display()))?
        {
            if inst.name == name {
                found.push(fname.to_string());
            }
        }
    }
    match found.len() {
        0 => Ok(None),
        1 => Ok(found.pop()),
        _ => Err(format!(
            "path: filesystem path {} has multiple children named {name:?}; cannot choose one",
            dir.display()
        )),
    }
}

fn existing_fragments(dir: &Path) -> Result<Vec<String>, String> {
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    let iter = std::fs::read_dir(dir).map_err(|e| format!("path: read {}: {e}", dir.display()))?;
    for entry in iter {
        let entry = entry.map_err(|e| format!("path: read {}: {e}", dir.display()))?;
        if let Some(name) = entry.file_name().to_str() {
            out.push(name.to_string());
        }
    }
    Ok(out)
}

fn is_syncable_child(node: &Value) -> bool {
    node_class(node)
        .map(|class| SYNCED_CLASSES.contains(&class))
        .unwrap_or(false)
}

fn find_tree_paths<'a>(tree: &'a Value, segs: &[String]) -> Vec<Vec<&'a Value>> {
    let mut out = Vec::new();
    for node in service_nodes(tree) {
        walk_tree_path(node, segs, 0, &mut Vec::new(), &mut out);
    }
    out
}

fn service_nodes(tree: &Value) -> Vec<&Value> {
    match tree {
        Value::Array(arr) => arr.iter().collect(),
        Value::Object(_) => tree
            .get("children")
            .and_then(|children| children.as_array())
            .map(|arr| arr.iter().collect())
            .unwrap_or_else(|| vec![tree]),
        _ => Vec::new(),
    }
}

fn walk_tree_path<'a>(
    node: &'a Value,
    segs: &[String],
    idx: usize,
    stack: &mut Vec<&'a Value>,
    out: &mut Vec<Vec<&'a Value>>,
) {
    if idx >= segs.len() || node_name(node) != Some(segs[idx].as_str()) {
        return;
    }
    stack.push(node);
    if idx + 1 == segs.len() {
        out.push(stack.clone());
    } else if let Some(children) = node.get("children").and_then(|v| v.as_array()) {
        for child in children {
            walk_tree_path(child, segs, idx + 1, stack, out);
        }
    }
    stack.pop();
}

fn one_tree_match<'a>(
    matches: Vec<Vec<&'a Value>>,
    display: &str,
) -> Result<Vec<&'a Value>, String> {
    match matches.len() {
        0 => Err(format!(
            "path: no Studio instance {display} found in tree.json"
        )),
        1 => Ok(matches.into_iter().next().unwrap()),
        n => Err(format!(
            "path: Studio path {display} is ambiguous in tree.json ({n} matches)"
        )),
    }
}

fn node_name(node: &Value) -> Option<&str> {
    node.get("name").and_then(|v| v.as_str())
}

fn node_class(node: &Value) -> Option<&str> {
    node.get("class")
        .or_else(|| node.get("className"))
        .and_then(|v| v.as_str())
}

fn node_has_children(node: &Value) -> bool {
    node.get("children")
        .and_then(|v| v.as_array())
        .map(|children| !children.is_empty())
        .unwrap_or(false)
}

fn resolve_fs_input(project: &Path, input: &str) -> Result<PathBuf, String> {
    let raw = Path::new(input);
    let joined = if raw.is_absolute() {
        raw.to_path_buf()
    } else {
        project.join(raw)
    };
    let normalized = normalize_lexical(&joined);
    if normalized.starts_with(project) {
        Ok(normalized)
    } else {
        let project_canon = project.canonicalize().ok();
        let path_canon = normalized.canonicalize().ok();
        match (project_canon, path_canon) {
            (Some(project_canon), Some(path_canon)) if path_canon.starts_with(&project_canon) => {
                Ok(path_canon)
            }
            _ => Ok(normalized),
        }
    }
}

fn absolute_lexical(path: &Path) -> Result<PathBuf, String> {
    let base = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .map_err(|e| format!("path: current directory: {e}"))?
            .join(path)
    };
    Ok(normalize_lexical(&base))
}

fn normalize_lexical(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                out.pop();
            }
            Component::Normal(part) => out.push(part),
            Component::RootDir | Component::Prefix(_) => out.push(component.as_os_str()),
        }
    }
    out
}

fn path_components(path: &Path) -> Result<Vec<String>, String> {
    let mut out = Vec::new();
    for component in path.components() {
        let Component::Normal(part) = component else {
            return Err(format!(
                "path: unsupported filesystem path {}",
                path.display()
            ));
        };
        let Some(s) = part.to_str() else {
            return Err(format!(
                "path: filesystem path {} is not UTF-8",
                path.display()
            ));
        };
        out.push(s.to_string());
    }
    Ok(out)
}

fn decode_fs_stem(stem: &str) -> String {
    let clean = parse_disambiguated(stem)
        .map(|(name, _)| name)
        .unwrap_or_else(|| stem.to_string());
    decode_name(&clean)
}

fn is_generated_root_file(components: &[String]) -> bool {
    components.len() == 1
        && matches!(
            components[0].as_str(),
            TREE_JSON | ".tree.json.tmp" | "ro-sync.md" | "CLAUDE.md" | "AGENTS.md"
        )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::fs;

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(tag: &str) -> Self {
            let p = std::env::temp_dir().join(format!(
                "rosync-path-{tag}-{}-{}",
                std::process::id(),
                unix_nanos()
            ));
            fs::create_dir_all(&p).unwrap();
            Self(p)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn unix_nanos() -> u128 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    }

    fn write_tree(project: &Path) {
        let tree = json!([
            {
                "class": "Workspace",
                "name": "Workspace",
                "children": [
                    { "class": "Part", "name": "Baseplate", "children": [] },
                    { "class": "Folder", "name": "Folder", "children": [
                        { "class": "Script", "name": "Runner", "children": [] }
                    ]}
                ]
            },
            {
                "class": "ReplicatedStorage",
                "name": "ReplicatedStorage",
                "children": [
                    { "class": "ModuleScript", "name": "Config", "children": [] },
                    { "class": "ModuleScript", "name": "Net", "children": [
                        { "class": "LocalScript", "name": "Client", "children": [] }
                    ]}
                ]
            }
        ]);
        fs::write(
            project.join(TREE_JSON),
            serde_json::to_string(&tree).unwrap(),
        )
        .unwrap();
    }

    #[test]
    fn studio_path_resolves_to_existing_script_file() {
        let d = TempDir::new("studio-file");
        write_tree(d.path());
        let rs = d.path().join("ReplicatedStorage");
        fs::create_dir_all(&rs).unwrap();
        fs::write(rs.join("Config.luau"), "return {}").unwrap();

        let resolved =
            resolve(d.path(), "ReplicatedStorage/Config", PathInputKind::Studio).unwrap();
        assert_eq!(resolved.class, "ModuleScript");
        assert_eq!(resolved.fs_path, rs.join("Config.luau"));
        assert!(resolved.fs_exists);
    }

    #[test]
    fn studio_path_predicts_script_with_children_directory() {
        let d = TempDir::new("studio-dir");
        write_tree(d.path());

        let resolved = resolve(d.path(), "ReplicatedStorage/Net", PathInputKind::Studio).unwrap();
        assert_eq!(resolved.class, "ModuleScript");
        assert_eq!(
            resolved.fs_path,
            d.path().join("ReplicatedStorage").join("Net")
        );
        assert!(!resolved.fs_exists);
    }

    #[test]
    fn filesystem_script_file_resolves_to_studio_path() {
        let d = TempDir::new("fs-file");
        write_tree(d.path());
        let rs = d.path().join("ReplicatedStorage");
        fs::create_dir_all(&rs).unwrap();
        fs::write(rs.join("Config.luau"), "return {}").unwrap();

        let resolved =
            resolve(d.path(), "ReplicatedStorage/Config.luau", PathInputKind::Fs).unwrap();
        assert_eq!(resolved.studio_path_string(), "ReplicatedStorage/Config");
        assert_eq!(resolved.class, "ModuleScript");
    }

    #[test]
    fn init_file_resolves_to_parent_script_instance() {
        let d = TempDir::new("init-file");
        write_tree(d.path());
        let net = d.path().join("ReplicatedStorage").join("Net");
        fs::create_dir_all(&net).unwrap();
        fs::write(net.join("init (Net).luau"), "return {}").unwrap();

        let resolved = resolve(
            d.path(),
            "ReplicatedStorage/Net/init (Net).luau",
            PathInputKind::Fs,
        )
        .unwrap();
        assert_eq!(resolved.studio_path_string(), "ReplicatedStorage/Net");
    }

    #[test]
    fn non_syncable_studio_path_is_rejected() {
        let d = TempDir::new("part");
        write_tree(d.path());

        let err = resolve(d.path(), "Workspace/Baseplate", PathInputKind::Studio).unwrap_err();
        assert!(err.contains("Studio-authoritative"), "{err}");
    }

    #[test]
    fn unresolved_filesystem_path_reports_likely_studio_path() {
        let d = TempDir::new("missing");
        write_tree(d.path());

        let err = resolve(
            d.path(),
            "ReplicatedStorage/Missing.luau",
            PathInputKind::Fs,
        )
        .unwrap_err();
        assert!(err.contains("maps to likely Studio path ReplicatedStorage/Missing"));
        assert!(err.contains("not present in tree.json"));
    }
}
