//! `rosync path` — translate between Studio instance paths and Ro-Sync files.

use crate::fs_map::{
    classify_script_file, decode_name, encode_name, is_init_file, parse_disambiguated,
    path_is_parent_init_source, path_to_instance_meta, InstanceDescriptor, PathFragmentAllocator,
    META_FILE,
};
use crate::fs_safety::{metadata_no_follow, validate_synced_path, PortableDirectoryIndex};
use crate::snapshot::{SYNCED_SERVICES, TREE_JSON};
use clap::ValueEnum;
use serde_json::Value;
use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};

#[derive(ValueEnum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum PathInputKind {
    /// Try Studio path first, then filesystem path.
    Auto,
    /// Interpret the input as a Studio instance path and print its filesystem path.
    Studio,
    /// Interpret the input as a filesystem path and print its Studio instance path.
    Fs,
}

impl PathInputKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Auto => "auto",
            Self::Studio => "studio",
            Self::Fs => "fs",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ResolvedPath {
    pub input_kind: PathInputKind,
    pub studio_path: Vec<String>,
    pub class: String,
    pub fs_path: PathBuf,
    pub fs_exists: bool,
}

impl ResolvedPath {
    pub fn studio_path_string(&self) -> String {
        self.studio_path.join("/")
    }
}

pub fn resolve_with_tree(
    project: &Path,
    tree: &Value,
    input: &str,
    from: PathInputKind,
) -> Result<ResolvedPath, String> {
    let project = absolute_lexical(project)?;
    match from {
        PathInputKind::Studio => studio_to_fs(&project, tree, input, PathInputKind::Studio),
        PathInputKind::Fs => fs_to_studio(&project, tree, input, PathInputKind::Fs),
        PathInputKind::Auto => {
            if looks_like_studio_path(tree, input) {
                studio_to_fs(&project, tree, input, PathInputKind::Studio)
            } else {
                fs_to_studio(&project, tree, input, PathInputKind::Fs)
            }
        }
    }
}

fn looks_like_studio_path(tree: &Value, input: &str) -> bool {
    let Some(segs) = parse_studio_path(input).ok() else {
        return false;
    };
    !find_tree_paths(tree, &segs).is_empty()
}

fn studio_to_fs(
    project: &Path,
    tree: &Value,
    input: &str,
    input_kind: PathInputKind,
) -> Result<ResolvedPath, String> {
    let segs = parse_studio_path(input)?;
    let matches = find_tree_paths(tree, &segs);
    let nodes = one_tree_match(matches, input)?;
    validate_syncable_studio_path(&nodes, input)?;

    let mut fs_path = project.to_path_buf();
    for (idx, node) in nodes.iter().enumerate() {
        let name = node_name(node).ok_or_else(|| "path: tree node missing name".to_string())?;
        if idx == 0 {
            fs_path = fs_path.join(encode_name(name));
            continue;
        }
        let parent = nodes[idx - 1];
        let fragment = child_fragment(project, &fs_path, parent, node)?;
        fs_path = fs_path.join(fragment);
    }
    validate_synced_path(project, &fs_path, true)
        .map_err(|error| format!("path: validate {}: {error}", fs_path.display()))?;

    Ok(ResolvedPath {
        input_kind,
        studio_path: segs,
        class: node_class(nodes[nodes.len() - 1]).unwrap_or("").to_string(),
        fs_exists: metadata_no_follow(&fs_path)
            .map_err(|error| format!("path: inspect {}: {error}", fs_path.display()))?
            .is_some(),
        fs_path,
    })
}

fn fs_to_studio(
    project: &Path,
    tree: &Value,
    input: &str,
    input_kind: PathInputKind,
) -> Result<ResolvedPath, String> {
    let fs_path = resolve_fs_input(project, input)?;
    let rel = fs_path.strip_prefix(project).map_err(|_| {
        format!(
            "path: filesystem path {} is outside project {}",
            fs_path.display(),
            project.display()
        )
    })?;
    let components = path_components(rel)?;
    if components.is_empty() {
        return Err("path: project root is not a Studio instance path".to_string());
    }

    if is_generated_root_file(&components) {
        return Err(format!(
            "path: {} is generated by Ro-Sync and is not a syncable Studio instance",
            fs_path.display()
        ));
    }

    let service = decode_fs_stem(&components[0]);
    if !SYNCED_SERVICES.contains(&service.as_str()) {
        return Err(format!(
            "path: {} is under unsynced top-level folder {:?}; synced services are: {}",
            fs_path.display(),
            components[0],
            SYNCED_SERVICES.join(", ")
        ));
    }
    validate_synced_path(project, &fs_path, true)
        .map_err(|error| format!("path: validate {}: {error}", fs_path.display()))?;

    let mut studio_path = vec![service];
    let mut stopped_at_init = false;
    for (idx, component) in components.iter().enumerate().skip(1) {
        let is_last = idx + 1 == components.len();
        let cur = project.join(components[..=idx].iter().collect::<PathBuf>());

        if is_init_file(component)
            && path_is_parent_init_source(&cur)
                .map_err(|error| format!("path: inspect init source {}: {error}", cur.display()))?
        {
            if !is_last {
                return Err(format!(
                    "path: init file {} describes its parent instance and cannot have children",
                    cur.display()
                ));
            }
            stopped_at_init = true;
            break;
        }

        let segment = if metadata_no_follow(&cur)
            .map_err(|error| format!("path: inspect {}: {error}", cur.display()))?
            .is_some()
        {
            let Some(inst) = path_to_instance_meta(&cur)
                .map_err(|e| format!("path: inspect filesystem path {}: {e}", cur.display()))?
            else {
                return Err(format!(
                    "path: {} is not a syncable Ro-Sync file or folder",
                    cur.display()
                ));
            };
            inst.name
        } else if let Some((_, stem)) = classify_script_file(component) {
            decode_fs_stem(&stem)
        } else if component.contains('.') {
            return Err(format!(
                "path: {} is not a syncable script file (.luau/.lua, .server.*, .client.*)",
                cur.display()
            ));
        } else {
            decode_fs_stem(component)
        };
        studio_path.push(segment);
    }

    if stopped_at_init && studio_path.len() == 1 {
        return Err(format!(
            "path: init file {} has no parent instance inside a synced service",
            fs_path.display()
        ));
    }

    let matches = find_tree_paths(tree, &studio_path);
    if matches.is_empty() {
        return Err(format!(
            "path: filesystem path {} maps to likely Studio path {}, but that path is not present in the live Studio tree",
            fs_path.display(),
            studio_path.join("/")
        ));
    }
    let nodes = one_tree_match(matches, &studio_path.join("/"))?;
    validate_syncable_studio_path(&nodes, &studio_path.join("/"))?;

    Ok(ResolvedPath {
        input_kind,
        studio_path,
        class: node_class(nodes[nodes.len() - 1]).unwrap_or("").to_string(),
        fs_exists: metadata_no_follow(&fs_path)
            .map_err(|error| format!("path: inspect {}: {error}", fs_path.display()))?
            .is_some(),
        fs_path,
    })
}

fn parse_studio_path(input: &str) -> Result<Vec<String>, String> {
    let trimmed = input.trim_matches('/');
    if trimmed.is_empty() {
        return Err("path: Studio path is empty; pass a service or descendant".to_string());
    }
    let segs: Vec<String> = trimmed.split('/').map(str::to_string).collect();
    if segs.iter().any(|s| s.is_empty()) {
        return Err(format!(
            "path: Studio path {input:?} contains an empty segment"
        ));
    }
    Ok(segs)
}

fn validate_syncable_studio_path(nodes: &[&Value], display: &str) -> Result<(), String> {
    let service = node_name(nodes[0]).unwrap_or("");
    if !SYNCED_SERVICES.contains(&service) {
        return Err(format!(
            "path: Studio path {display} is under unsynced service {service}; synced services are: {}",
            SYNCED_SERVICES.join(", ")
        ));
    }
    if nodes.len() == 1 {
        return Ok(());
    }
    let class = node_class(nodes[nodes.len() - 1]).unwrap_or("");
    if !crate::sync_scope::contains(class) {
        return Err(format!(
            "path: Studio path {display} is a {class}, which is Studio-authoritative and has no filesystem path. Syncable classes: {}",
            crate::sync_scope::CLASSES.join(", ")
        ));
    }
    Ok(())
}

fn child_fragment(
    project: &Path,
    parent_dir: &Path,
    parent_node: &Value,
    child_node: &Value,
) -> Result<String, String> {
    let name = node_name(child_node).ok_or_else(|| "path: tree node missing name".to_string())?;
    let existing = existing_fragment_index(parent_dir)?;
    if let Some(existing) = unique_existing_fragment(parent_dir, name, &existing.by_name)? {
        return Ok(existing);
    }

    let mut allocator =
        PathFragmentAllocator::from_taken(existing.fragments.iter().map(String::as_str));

    let Some(children) = parent_node.get("children").and_then(|v| v.as_array()) else {
        return Err(format!(
            "path: tree node {} has no children to resolve {}",
            node_name(parent_node).unwrap_or("?"),
            name
        ));
    };
    for sibling in children {
        if std::ptr::eq(sibling, child_node) {
            break;
        }
        if !is_syncable_child(sibling) {
            continue;
        }
        let Some(sibling_name) = node_name(sibling) else {
            continue;
        };
        if unique_existing_fragment(parent_dir, sibling_name, &existing.by_name)?.is_some() {
            continue;
        }
        allocator.allocate(&InstanceDescriptor {
            class: node_class(sibling).unwrap_or(""),
            name: sibling_name,
            has_children: node_has_children(sibling),
        });
    }

    let fragment = allocator.allocate(&InstanceDescriptor {
        class: node_class(child_node).unwrap_or(""),
        name,
        has_children: node_has_children(child_node),
    });

    let path = parent_dir.join(&fragment.fragment);
    validate_synced_path(project, &path, true)
        .map_err(|error| format!("path: validate resolved path {}: {error}", path.display()))?;
    Ok(fragment.fragment)
}

struct ExistingFragmentIndex {
    fragments: Vec<String>,
    by_name: HashMap<String, Vec<String>>,
}

fn existing_fragment_index(dir: &Path) -> Result<ExistingFragmentIndex, String> {
    let Some(metadata) = metadata_no_follow(dir)
        .map_err(|error| format!("path: inspect {}: {error}", dir.display()))?
    else {
        return Ok(ExistingFragmentIndex {
            fragments: Vec::new(),
            by_name: HashMap::new(),
        });
    };
    if !metadata.is_dir() {
        return Err(format!("path: expected directory: {}", dir.display()));
    }
    let mut fragments = Vec::new();
    let mut by_name: HashMap<String, Vec<String>> = HashMap::new();
    let index = PortableDirectoryIndex::read(dir)
        .map_err(|error| format!("path: read {}: {error}", dir.display()))?;
    for entry in index.entries() {
        fragments.push(entry.fragment.clone());
        if entry.fragment == META_FILE {
            continue;
        }
        if let Some(inst) = path_to_instance_meta(&entry.path)
            .map_err(|e| format!("path: inspect {}: {e}", entry.path.display()))?
        {
            by_name
                .entry(inst.name)
                .or_default()
                .push(entry.fragment.clone());
        }
    }
    Ok(ExistingFragmentIndex { fragments, by_name })
}

fn unique_existing_fragment(
    dir: &Path,
    name: &str,
    index: &HashMap<String, Vec<String>>,
) -> Result<Option<String>, String> {
    let found = index.get(name).map(Vec::as_slice).unwrap_or(&[]);
    match found.len() {
        0 => Ok(None),
        1 => Ok(Some(found[0].clone())),
        _ => Err(format!(
            "path: filesystem path {} has multiple children named {name:?}; cannot choose one",
            dir.display()
        )),
    }
}

fn is_syncable_child(node: &Value) -> bool {
    node_class(node)
        .map(crate::sync_scope::contains)
        .unwrap_or(false)
}

fn find_tree_paths<'a>(tree: &'a Value, segs: &[String]) -> Vec<Vec<&'a Value>> {
    let mut out = Vec::new();
    for node in service_nodes(tree) {
        walk_tree_path(node, segs, 0, &mut Vec::new(), &mut out);
    }
    out
}

fn service_nodes(tree: &Value) -> Vec<&Value> {
    match tree {
        Value::Array(arr) => arr.iter().collect(),
        Value::Object(_) => tree
            .get("children")
            .and_then(|children| children.as_array())
            .map(|arr| arr.iter().collect())
            .unwrap_or_else(|| vec![tree]),
        _ => Vec::new(),
    }
}

fn walk_tree_path<'a>(
    node: &'a Value,
    segs: &[String],
    idx: usize,
    stack: &mut Vec<&'a Value>,
    out: &mut Vec<Vec<&'a Value>>,
) {
    if idx >= segs.len() || node_name(node) != Some(segs[idx].as_str()) {
        return;
    }
    stack.push(node);
    if idx + 1 == segs.len() {
        out.push(stack.clone());
    } else if let Some(children) = node.get("children").and_then(|v| v.as_array()) {
        for child in children {
            walk_tree_path(child, segs, idx + 1, stack, out);
        }
    }
    stack.pop();
}

fn one_tree_match<'a>(
    matches: Vec<Vec<&'a Value>>,
    display: &str,
) -> Result<Vec<&'a Value>, String> {
    match matches.len() {
        0 => Err(format!(
            "path: no Studio instance {display} found in the live Studio tree"
        )),
        1 => Ok(matches.into_iter().next().unwrap()),
        n => Err(format!(
            "path: Studio path {display} is ambiguous in the live Studio tree ({n} matches)"
        )),
    }
}

fn node_name(node: &Value) -> Option<&str> {
    node.get("name").and_then(|v| v.as_str())
}

fn node_class(node: &Value) -> Option<&str> {
    node.get("class")
        .or_else(|| node.get("className"))
        .and_then(|v| v.as_str())
}

fn node_has_children(node: &Value) -> bool {
    node.get("children")
        .and_then(|v| v.as_array())
        .map(|children| !children.is_empty())
        .unwrap_or(false)
}

fn resolve_fs_input(project: &Path, input: &str) -> Result<PathBuf, String> {
    let raw = Path::new(input);
    let joined = if raw.is_absolute() {
        raw.to_path_buf()
    } else {
        project.join(raw)
    };
    let normalized = normalize_lexical(&joined);
    if !normalized.starts_with(project) {
        return Err(format!(
            "path: filesystem path {} is outside project {}",
            normalized.display(),
            project.display()
        ));
    }
    Ok(normalized)
}

fn absolute_lexical(path: &Path) -> Result<PathBuf, String> {
    let base = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .map_err(|e| format!("path: current directory: {e}"))?
            .join(path)
    };
    Ok(normalize_lexical(&base))
}

fn normalize_lexical(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                out.pop();
            }
            Component::Normal(part) => out.push(part),
            Component::RootDir | Component::Prefix(_) => out.push(component.as_os_str()),
        }
    }
    out
}

fn path_components(path: &Path) -> Result<Vec<String>, String> {
    let mut out = Vec::new();
    for component in path.components() {
        let Component::Normal(part) = component else {
            return Err(format!(
                "path: unsupported filesystem path {}",
                path.display()
            ));
        };
        let Some(s) = part.to_str() else {
            return Err(format!(
                "path: filesystem path {} is not UTF-8",
                path.display()
            ));
        };
        out.push(s.to_string());
    }
    Ok(out)
}

fn decode_fs_stem(stem: &str) -> String {
    let clean = parse_disambiguated(stem)
        .map(|(name, _)| name)
        .unwrap_or_else(|| stem.to_string());
    decode_name(&clean)
}

fn is_generated_root_file(components: &[String]) -> bool {
    components.len() == 1
        && matches!(
            components[0].as_str(),
            TREE_JSON | ".tree.json.tmp" | "ro-sync.md" | "CLAUDE.md" | "AGENTS.md"
        )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::fs;

    struct TempDir(tempfile::TempDir);

    impl TempDir {
        fn new(tag: &str) -> Self {
            Self(
                tempfile::Builder::new()
                    .prefix(&format!("rosync-path-{tag}-"))
                    .tempdir()
                    .unwrap(),
            )
        }

        fn path(&self) -> &Path {
            self.0.path()
        }
    }

    fn test_tree() -> Value {
        json!([
            {
                "class": "Workspace",
                "name": "Workspace",
                "children": [
                    { "class": "Part", "name": "Baseplate", "children": [] },
                    { "class": "Folder", "name": "Folder", "children": [
                        { "class": "Script", "name": "Runner", "children": [] }
                    ]}
                ]
            },
            {
                "class": "ReplicatedStorage",
                "name": "ReplicatedStorage",
                "children": [
                    { "class": "ModuleScript", "name": "Config", "children": [] },
                    { "class": "ModuleScript", "name": "Net", "children": [
                        { "class": "LocalScript", "name": "Client", "children": [] }
                    ]}
                ]
            }
        ])
    }

    fn resolve(project: &Path, input: &str, from: PathInputKind) -> Result<ResolvedPath, String> {
        resolve_with_tree(project, &test_tree(), input, from)
    }

    #[test]
    fn studio_path_resolves_to_existing_script_file() {
        let d = TempDir::new("studio-file");
        let rs = d.path().join("ReplicatedStorage");
        fs::create_dir_all(&rs).unwrap();
        fs::write(rs.join("Config.luau"), "return {}").unwrap();

        let resolved =
            resolve(d.path(), "ReplicatedStorage/Config", PathInputKind::Studio).unwrap();
        assert_eq!(resolved.class, "ModuleScript");
        assert_eq!(resolved.fs_path, rs.join("Config.luau"));
        assert!(resolved.fs_exists);
    }

    #[test]
    fn studio_path_predicts_script_with_children_directory() {
        let d = TempDir::new("studio-dir");

        let resolved = resolve(d.path(), "ReplicatedStorage/Net", PathInputKind::Studio).unwrap();
        assert_eq!(resolved.class, "ModuleScript");
        assert_eq!(
            resolved.fs_path,
            d.path().join("ReplicatedStorage").join("Net")
        );
        assert!(!resolved.fs_exists);
    }

    #[test]
    fn studio_path_resolves_across_tens_of_thousands_of_wide_siblings() {
        const WIDTH: usize = 20_000;
        let d = TempDir::new("studio-wide");
        let children = (0..WIDTH)
            .map(|index| {
                json!({
                    "class": "ModuleScript",
                    "name": format!("Item{index:05}"),
                    "children": []
                })
            })
            .collect::<Vec<_>>();
        let tree = json!([{
            "class": "ReplicatedStorage",
            "name": "ReplicatedStorage",
            "children": children
        }]);

        let resolved = resolve_with_tree(
            d.path(),
            &tree,
            "ReplicatedStorage/Item19999",
            PathInputKind::Studio,
        )
        .unwrap();

        assert_eq!(
            resolved.fs_path,
            d.path().join("ReplicatedStorage").join("Item19999.luau")
        );
        assert!(!resolved.fs_exists);
    }

    #[test]
    fn filesystem_script_file_resolves_to_studio_path() {
        let d = TempDir::new("fs-file");
        let rs = d.path().join("ReplicatedStorage");
        fs::create_dir_all(&rs).unwrap();
        fs::write(rs.join("Config.luau"), "return {}").unwrap();

        let resolved =
            resolve(d.path(), "ReplicatedStorage/Config.luau", PathInputKind::Fs).unwrap();
        assert_eq!(resolved.studio_path_string(), "ReplicatedStorage/Config");
        assert_eq!(resolved.class, "ModuleScript");
    }

    #[test]
    fn init_file_resolves_to_parent_script_instance() {
        let d = TempDir::new("init-file");
        let net = d.path().join("ReplicatedStorage").join("Net");
        fs::create_dir_all(&net).unwrap();
        fs::write(net.join("init (Net).luau"), "return {}").unwrap();

        let resolved = resolve(
            d.path(),
            "ReplicatedStorage/Net/init (Net).luau",
            PathInputKind::Fs,
        )
        .unwrap();
        assert_eq!(resolved.studio_path_string(), "ReplicatedStorage/Net");
    }

    #[test]
    fn mismatched_named_init_resolves_to_literal_child() {
        let d = TempDir::new("mismatched-init-leaf");
        let misc = d.path().join("ReplicatedStorage").join("Misc");
        fs::create_dir_all(&misc).unwrap();
        fs::write(misc.join("init (Misc).luau"), "return 'parent'").unwrap();
        fs::write(
            misc.join("init (Notifications).luau"),
            "return 'literal child'",
        )
        .unwrap();
        let tree = json!([{
            "class": "ReplicatedStorage",
            "name": "ReplicatedStorage",
            "children": [{
                "class": "ModuleScript",
                "name": "Misc",
                "children": [{
                    "class": "ModuleScript",
                    "name": "init (Notifications)",
                    "children": []
                }]
            }]
        }]);

        let resolved = resolve_with_tree(
            d.path(),
            &tree,
            "ReplicatedStorage/Misc/init (Notifications).luau",
            PathInputKind::Fs,
        )
        .unwrap();

        assert_eq!(
            resolved.studio_path_string(),
            "ReplicatedStorage/Misc/init (Notifications)"
        );
        assert_eq!(resolved.class, "ModuleScript");
    }

    #[test]
    fn non_syncable_studio_path_is_rejected() {
        let d = TempDir::new("part");

        let err = resolve(d.path(), "Workspace/Baseplate", PathInputKind::Studio).unwrap_err();
        assert!(err.contains("Studio-authoritative"), "{err}");
    }

    #[test]
    fn unresolved_filesystem_path_reports_likely_studio_path() {
        let d = TempDir::new("missing");

        let err = resolve(
            d.path(),
            "ReplicatedStorage/Missing.luau",
            PathInputKind::Fs,
        )
        .unwrap_err();
        assert!(err.contains("maps to likely Studio path ReplicatedStorage/Missing"));
        assert!(err.contains("not present in the live Studio tree"));
    }
}
